### ISSUE TITLE
To get output in which length is not 1024

### ISSUE THREAD

**Issue by KinamSalad** [allenai/bilm-tf#136]
First Thank you for your help, I can train the bilstm and apply to elmo!

However, There is an another question:(, I want to get the embedded output as 128 length. 

Where can I modify? Is it possible that i modify the filters in train_elmo.py?

ex) 
from
     'filters': [[1, 32],
       [2, 32],
       [3, 64],
       [4, 128],
       [5, 256],
       [6, 512],
       [7, 1024]],
to
 'filters': [[1, 32],
       [2, 32],
       [3, 64],
       [4, 128]],

projection_dim : 512 -> 64 (which is half of 1024)

thank you!

**Comment by matt-peters** [comment]
The filters key specifies the character CNN filters.

To reduce the output dimension, you need to change the `projection_dim`. 

Here's an example of a smaller config that reduces the LSTM hidden size to 1024, the output dimension to 128 (in each direction), and only includes one highway layer instead of two:

```
{'char_cnn': {'activation': 'relu',
  'embedding': {'dim': 16},
  'filters': [[1, 32],
   [2, 32],
   [3, 64],
   [4, 128],
   [5, 256],
   [6, 512],
   [7, 1024]],
  'max_characters_per_token': 50,
  'n_characters': 261,
  'n_highway': 1},
 'lstm': {'cell_clip': 3,
  'dim': 1024,
  'n_layers': 2,
  'proj_clip': 3,
  'projection_dim': 128,
  'use_skip_connections': True}}
```
