### ISSUE TITLE
Why ELMo's word embedding can represent the word better than glove?

### ISSUE THREAD

**Issue by guotong1988** [allenai/bilm-tf#139]
Based on my understanding, ELMo first init an word embedding matrix `A` for all the word and then add LSTM `B`, at end use the LSTM `B`'s outputs to predict each word's next word.

I am wondering why we can input each word in the vocab and get the final word representation from the word embedding matrix `A` after training.

It seems that we lost the information of LSTM `B`.

Why the embedding can contains the information we want in the language model.

Why the training process can inject the information for a good word representation into the word embedding matrix `A`?

Thank you!

**Comment by PhilipMay** [comment]
From my understanding glove is a static word to vector map. ELMO / bilm is a deep contextualized word representation. It calculates a vector for a word "on runtime" and with the context of the whole sentence. Not just the word in isolation. Also because of its character n gram view it can create vectors for words it has never seen before. This is all impossible for glove - which is just a map at the end of the day.

**Comment by matt-peters** [comment]
The contextualized representations use the LSTM layers so that information is not lost.

**Comment by pzhang84** [comment]
@PhilipMay According to you, 'It calculates a vector for a word "on runtime" and with the context of the whole sentence.' Does that also explain why ELMo produces different embeddings for one sentence if I run it several times (the embedding matrix is close though)?
