### ISSUE TITLE
What happens in case of OOV character?

### ISSUE THREAD

**Issue by mihirkale815** [allenai/bilm-tf#46]
Does the model break if it sees an out of vocabulary character?

**Comment by matt-peters** [comment]
No it shouldn't break, as in the model will produce an output instead of raising an exception.  The character vocabulary class will map all characters into a valid range.

OOV characters may get mapped to an entry in the character embedding matrix with parameters that have not been modified during the training process, and as such are still set to their initialized value. This will be a small random number, so likely won't impact the model performance.  In practice, I've never noticed a problem with OOV characters, but also haven't spent any time investigating them.
