### ISSUE TITLE
InvalidArgumentError (see above for traceback): Sampler's range is too small.

### ISSUE THREAD

**Issue by goingcoder** [allenai/bilm-tf#75]
hello, I encounter an problem, “tensorflow.python.framework.errors_impl.InvalidArgumentError: Sampler's range is too small.
	 [[Node: lm/sampled_softmax_loss_1/LogUniformCandidateSampler = LogUniformCandidateSampler[num_sampled=8192, num_true=1, range_max=6603, seed=0, seed2=0, unique=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](lm/Reshape_6, ^lm/dropout_1/mul)]]
”。
I want to train based on words without chars.So I changed the code like "load_vocab(args.vocab_file)"
And I remove CNN in dict.I don't know why.

**Comment by felixwzh** [comment]
I had the same problem today and I think I solved it.
This is because the `num_sampled` (8192 in your case) should be smaller than the `range_max` (6603 in your case), see this [page, line56](https://github.com/tensorflow/tensorflow/blob/982549ea3423df4270ff154e5c764beb43d472da/tensorflow/core/kernels/candidate_sampler_ops.cc).
You can fix this problem by setting `n_negative_samples_batch` in `train_elmo.py` smaller than your vocabulary size.

**Comment by matt-peters** [comment]
That's right.  FWIW, with such a small vocabulary size, you will almost certainly have better results without sacrificing training time if you switch to a unsampled, full softmax.
