### ISSUE TITLE
LSTM weight shapes

### ISSUE THREAD

**Issue by chledowski** [allenai/bilm-tf#96]
Hi,

Thank you very much for your great work!

We are trying to load your largest embeddings into our keras model. Unfortunately, the shapes of weight in the weight file are not the shapes we have expected:

```B (16384,)
W_0 (1024, 16384)
W_P_0 (4096, 512)
```

Where we have:
```(512, 16384)
(4096, 16384),
(4096, 512)
```
first for input (4 times (512,4096)) and then for hidden layer (4 times (4096,4096)), and last for projection (which is ok)

We have two questions:
- why do you have (1024, 16384), while the input shape is 512
- why there are no weights for hidden layers (4096, 16384)?

Thanks,
Kuba

**Comment by matt-peters** [comment]
The shapes and names of the weights are due to the low level details of the particular (old) tensorflow version used to train the model.

The best reference I can give to unpacking them into another form is the allennlp code that reads them and instantiates pytorch versions: https://github.com/allenai/allennlp/blob/master/allennlp/modules/elmo_lstm.py#L243

Does that help?

**Comment by chledowski** [comment]
Thanks for your quick response!

It turned out that in the LSTMs there is another projection layer that projects hidden states from 4096 to 512. Therefore the shape of W_0: (1024, 16384) contains W_h and W_x concatenated.

Thanks for your help!
